[gcp_service_account]
type = "service_account"
project_id = "hand-hygiene-new"
private_key_id = "e0b87a4bc1ecc954c4969d9aff269f15df2410d5"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDPJOpwvFOxcRU9
HZzkF2/mH7zQGJomVE2s4OFhIK1bKU864QYNELm1XKTVfCLfJlHKFi9nebiWXnEs
G+2yq5M35rpPtNG6zHTBJ9AG4z5fUxtplQVl1Pigb2fAcRmN/d9Rs77FpYMOPHNz
B9kzYd1Ml2jpPtQju8VIebhNB3J0586O0GOZvv26AKQlCqOSTx6wcLtd77maFNfU
178gcU9UyXgPiGDQI1RdNCbDkm7qK+qKSt4PfEPLREuPRRLEflrmDhr24GPhCuNV
l0+IbNJQi76+sK+U0cWu14lgytDEOFUCvtJ47YAdUzoRkXhD4lKaaGF9mdR5MdiU
asnU4n8rAgMBAAECggEAERSeMEWXMR59/dgfQ7+a/oLHcvFUZKy26vZwHy4unUG+
wsAjW5hxd7736JKf3X6vZ9aEeifTTLLk6hozc3QqY4Wm/0ONt7V8OyEpSiga0Ilt
zTr4gvkYt0H4cCnjTY4NiBMmO+317IqXinivNElxkgs6H2GK5JdrIRrIU7G1gmYk
t6hZ+MD9bP9Nb9kmqKx5ZmsliB7Kb4e7sU22PhGtPl+eaHyG+8zBxdj5IZJDEkmO
Al5a4rot12IzY8ZXs0bGya9bD3Cp7mCb8fBKRlEZdIH9vXGBUIqOGBP7Y89sRAgL
UYhOztkpyTI6lLsydwr5dn6t4zlVsjvOYsWe7k2BAQKBgQD/dFFrC7zERpg8ggT/
9MrKyHLX6tvOxPqxQOB6X9nl76O/47KBsnaCLsGv/UKUPH2PMI6PuMfUryAnAqkG
C8haf+7XqIDcOWpeM0tPibecTlyU5eRFB5DvicXeAikkcxTIcoAncAfxfKZW/eIA
vu6AZYR2Ot5/dJatcQIpXoSoCwKBgQDPli6M31lJRhXcl4ezESV8IWGP62NhuMP4
SyKu4G3yNDfflHvjpe4ezRvqbptuEze49jyH5GRxT00hbID6Q63Bd3Qeaaw1Rbrw
Q6LGpUxvKHy/YXS91IHlXmLLyDu5auUMZN6UtwnotndFqRu0DL9/hQmb9siNgZkO
BjofC3lZYQKBgQDYyJ1PemZ3KnGG58/WZqax7+mF0ok2r3MPeT8GmtEPkI4mCdUy
u4BWeddkwkf+BFeJbGuPDACJPRTMBjXqK5WbN3Y5DYZNXWwnBOCkXvqyas2mjnFp
I0KcBQ8lmC/R/tdkQ8b9sNUM2ftPV6SzfVRpIb2Hl+25u/ciuQRclxl8gQKBgQCg
J1vur3pxP7MqJ3Y4PuhOpmpg4Ngh0qzO6RjvFpN8o7Dfu+0BK0lVViVNbtxXxlfd
SYxVw22Cxg3Z1Z6Edqaddo2N0TVdPFkHeQcifvFDaVclSAkLU+KLlZBfbDI30TK5
pzDaR4VLl0rZ4ahP9u3fckKBo5oDIpN08HTy8qVCwQKBgQCtjUMJYWd6Qgm2QDx8
OyadGeubIW1uKGto1HEsZVLcwUCCW1/mWQlSSxWUNXxHuflnZhM3cFs2xLyjHPxo
WNVEUwu99CPjvPlvRFmS5q2IBnHCuEc+MeuCCGK6DJhwLgH3TZ3S9nUoyfnedknb
RYxTCrBQm2aRlxd2uKl2Noj9xw==
-----END PRIVATE KEY-----"""
client_email = "audit-bot@hand-hygiene-new.iam.gserviceaccount.com"
client_id = "109324850032508334357"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/audit-bot%40hand-hygiene-new.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
